# Generated by Django 4.1.5 on 2023-01-21 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0005_product_stock"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(null=True, upload_to="static/products_images/"),
        ),
    ]
