# Generated by Django 4.1.5 on 2023-02-28 21:33

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0006_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(null=True, upload_to=base.models.upload_path),
        ),
    ]
